name: 'CKEditor custom config'
type: module
description: 'Extends core CKEditor to support custom configuration.'
package: Custom
core_version_requirement: ^8 || ^9 || ^10

dependencies:
  - ckeditor:ckeditor

# Information added by Drupal.org packaging script on 2023-02-17
version: '8.x-3.3'
project: 'ckeditor_config'
datestamp: 1676656753
