<?php

/**
 * @file
 * Contains kidiklik_front_contact.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Database\Database;
use Drupal\Core\Database\Connection;

/**
 * Implements hook_help().
 */
function kidiklik_front_contact_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the kidiklik_front_contact module.
    case 'help.page.kidiklik_front_contact':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Contact message') . '</p>';
      return $output;

    default:
  }
}


function kidiklik_front_contact_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  if ($form_id == "node_message_contact_form") {
    $form["#validate"][] = "kidiklik_front_contact_validate_contact_form";
    
    \Drupal::service('kidiklik.service')->banip();
    
    /*
    $database->query('insert into banip (ip) values ("'.$ip.'")');
    $query = $database->query('select * from franceip');
    $result = $query->fetchAll();
    */


  }

}

function kidiklik_front_contact_validate_contact_form($form, FormStateInterface $form_state)
{
  \Drupal::service('kidiklik.service')->banip();

    $test = current($form_state->getValue('field_age'))['value'] ?? null;
    if(!empty($test)) {
        $form_state->setErrorByName('kidiklik_contact', 'Une erreur est survenue !');
    }
}
