<?php

/**
 * @file
 * Contains kidiklik_front_contact.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Database\Database;
use Drupal\Core\Database\Connection;

/**
 * Implements hook_help().
 */
function kidiklik_front_contact_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the kidiklik_front_contact module.
    case 'help.page.kidiklik_front_contact':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Contact message') . '</p>';
      return $output;

    default:
  }
}


function kidiklik_front_contact_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  if ($form_id == "node_message_contact_form") {
    $page_dep = \Drupal::service('kidiklik.service')->getPageDepartement();
    if (!empty($page_dep)) {
      $renderer = \Drupal::service("renderer");
      $variables['coordonnee'] = [
        '#markup' => sprintf('<p><b class="bleu titre_h1">Coordonnées</b></p><b>Nom :</b> %s<br><b>Téléphone :</b> <a href="tel:%s">%s</a><br><b>E-mail :</b> <a href="mailto:%s">%s</a>',
          $page_dep->get('field_societe')->value,
          $page_dep->get('field_telephone')->value,
          $page_dep->get('field_telephone')->value,
          $page_dep->get('field_e_mail')->value,
          $page_dep->get('field_e_mail')->value
        ),
      ];


      $form["coordonnees"] = [
        "#type" => "html_tag",
        "#tag" => "div",
        "#value" => $renderer->render($variables['coordonnee'])->__toString(),
        "#attributes" => [
          "class" => [
            "jumbotron", "mt-4 pt-3 pb-3"
          ]
        ],
        "#weight" => 0,
      ];
    }

    $form["#validate"][] = "kidiklik_front_contact_validate_contact_form";
    $form["#attached"]["library"][] = "kidiklik_front_contact/kidiklik_front_contact.actions";

    \Drupal::service('kidiklik.service')->banip();

  }

}

function kidiklik_front_contact_validate_contact_form($form, FormStateInterface $form_state)
{

}
